# Feature Selection 
This module is generally used for feature selection and feature transformation which helps us to overcome the problem of curse of dimentionality and improve estimators’ accuracy scores or to boost their performance on very high-dimensional datasets

In [1]:
import pandas as pd
import featureselection as fs
import muloutlier as ml
a = pd.read_csv('sample data.csv')

//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


### varthres(dataset,threshold)
To select the columns based on the value of their varience which is greater then the threhold but only numeric dataset should be passed to this function . It will return the altered dataset in the form numpy array 

In [7]:
for i in a:
    ##print i
    a = ml.transform(a,i) ## To transform textual data into numeric form 
a.head()

Customer  State  Customer Lifetime Value  Response  Coverage  Education  \
0            0      0              2763.519279         0         0          0   
1            1      1              6979.535903         0         1          0   
2            2      2             12887.431650         0         2          0   
3            3      3              7645.861827         0         0          0   
4            4      0              2813.692575         0         0          0   
5            5      4              8256.297800         1         0          0   
6            6      4              5380.898636         1         0          1   
7            7      1              7216.100311         0         2          2   
8            8      4             24127.504020         1         0          0   
9            9      4              7388.178085         0         1          1   
10          10      3              4738.992022         0         0          1   
11          11      3              8197.197078         0         0          1   
12          12      3              8798.797003         0         2          2   
13          13      1              8819.018934         1         0          3   
14          14      3              5384.431665         0         0          1   
15          15      4              7463.139377         0         0          0   
16          16      2              2566.867823         0         0          3   
17          17      3              3945.241604         0         0          1   
18          18      4              5710.333115         0         0          1   
19          19      3              8162.617053         0         2          3   
20          20      4              2872.051273         0         0          3   
21          21      0              3041.791561         0         1          0   
22          22      1             24127.504020         1         0          0   
23          23      2              2450.190996         0         0          0   
24          24      3              2392.107890         0         0          0   
25          25      4              5802.065978         0         0          1   
26          26      3              3946.372085         0         2          0   
27          27      0              5346.916576         0         1          2   
28          28      1             12902.560140         0         2          1   
29          29      4              3235.360468         0         1          2   
...        ...    ...                      ...       ...       ...        ...   
9104      9104      3              2615.139220         0         0          1   
9105      9105      3              5551.398167         0         1          1   
9106      9106      3              6827.044423         0         0          3   
9107      9107      3              5619.689084         1         2          3   
9108      9108      3              3907.028747         0         0          3   
9109      9109      3              3622.872124         0         0          1   
9110      9110      3             34611.378960         1         0          3   
9111      9111      3              2845.520933         0         0          0   
9112      9112      3              5500.577411         0         1          1   
9113      9113      3              3358.532935         0         1          0   
9114      9114      3              7501.661322         0         1          3   
9115      9115      3             11663.985720         0         2          1   
9116      9116      3              5133.397765         0         0          3   
9117      9117      3              8732.090534         0         0          3   
9118      9118      3              9424.256842         0         0          2   
9119      9119      3              5479.555081         1         0          2   
9120      9120      3              2114.738469         0         0          0   
9121      9121      3              41

In [5]:
fs.varthres(a,0.5)

array([[  0.00000000e+00,   0.00000000e+00,   2.76351928e+03, ...,
          0.00000000e+00,   3.84811147e+02,   0.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   6.97953590e+03, ...,
          0.00000000e+00,   1.13146493e+03,   1.00000000e+00],
       [  2.00000000e+00,   2.00000000e+00,   1.28874317e+04, ...,
          0.00000000e+00,   5.66472247e+02,   0.00000000e+00],
       ..., 
       [  9.13100000e+03,   3.00000000e+00,   8.16389043e+03, ...,
          3.00000000e+00,   7.90784983e+02,   1.00000000e+00],
       [  9.13200000e+03,   3.00000000e+00,   7.52444244e+03, ...,
          3.00000000e+00,   6.91200000e+02,   1.00000000e+00],
       [  9.13300000e+03,   3.00000000e+00,   2.61183687e+03, ...,
          1.00000000e+00,   3.69600000e+02,   0.00000000e+00]])

### Kbest(df,features,class1,arr):
It is used to select arr number of best features based on chi test compared between features and  class1 which indicate the class to be predicted . Here df is the dataframe used . It only accepts features in numeric form . It returns the altered dataset in numpy array form and features which are selected  .

In [8]:
fs.Kbest(a,['State','Gender','Income','Location Code','Policy'],'Vehicle Class',4)

['State', 'Gender', 'Income', 'Location Code']


(array([[    0,     0, 56274,     0],
        [    1,     0,     0,     0],
        [    2,     0, 48767,     0],
        ..., 
        [    3,     1,     0,     0],
        [    3,     1, 21941,     0],
        [    3,     1,     0,     0]]),
 ['State', 'Gender', 'Income', 'Location Code'])

### Pca(dataset,features,numberofcomponenets):
It is used to apply the Principle component analysis for the given dataset with these features transforming it into data with number of componenets 
Output : A transformed output numpy array

In [9]:
fs.Pca(a,['State','Gender','Income','Location Code','Policy'],4)

[[ -1.86166200e+04   2.70184277e+00   2.59462077e+00   6.67587355e-01]
 [  3.76573800e+04   1.76401617e+00   1.58622549e+00   8.31093580e-02]
 [ -1.11096200e+04   1.73807066e+00   5.80801241e-01   5.95269946e-01]
 ..., 
 [  3.76573800e+04   7.92411112e-01  -4.30373894e-01   2.03867738e-01]
 [  1.57163800e+04  -3.22552214e+00  -4.92507771e-01   4.32218886e-01]
 [  3.76573800e+04   2.79218632e+00  -4.00553865e-01   2.04207540e-01]]


array([[ -1.86166200e+04,   2.70184277e+00,   2.59462077e+00,
          6.67587355e-01],
       [  3.76573800e+04,   1.76401617e+00,   1.58622549e+00,
          8.31093580e-02],
       [ -1.11096200e+04,   1.73807066e+00,   5.80801241e-01,
          5.95269946e-01],
       ..., 
       [  3.76573800e+04,   7.92411112e-01,  -4.30373894e-01,
          2.03867738e-01],
       [  1.57163800e+04,  -3.22552214e+00,  -4.92507771e-01,
          4.32218886e-01],
       [  3.76573800e+04,   2.79218632e+00,  -4.00553865e-01,
          2.04207540e-01]])

### Ica(dataset)
To do feature transformation such as all features are independent from one another 
Input : Dataset is the input 
output : Transformed dataset in the form of numpy array where features are independent from one another 

In [10]:
fs.Ica(a)

//anaconda/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py:116: UserWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn('FastICA did not converge. Consider increasing '


array([[ 0.01832463, -0.00635411, -0.01686468, ...,  0.01166417,
        -0.01480042,  0.01595473],
       [-0.00319014, -0.00304023, -0.00171987, ..., -0.00090049,
        -0.00094042,  0.01734679],
       [-0.00334217, -0.00704632, -0.00451143, ...,  0.01140977,
        -0.01461874,  0.01684027],
       ..., 
       [ 0.01872353, -0.00180152, -0.00524813, ...,  0.01145152,
         0.00116338, -0.0165438 ],
       [-0.0046689 , -0.01150949, -0.0164422 , ...,  0.00320315,
        -0.0016021 , -0.01757311],
       [ 0.01904211,  0.00019267,  0.01767571, ..., -0.01920169,
        -0.00980256, -0.0165948 ]])